"""Generate a paper-ready methods document (results/methods.md) from the pipeline.

Combines a hand-written narrative of every model component and its formulas with results,
parameters, and catalogue tables filled in from the live run — so the document always matches
the code. Regenerated by `make run`.
"""
from __future__ import annotations

from typing import Any

from . import config


def _m(node: dict) -> str:
    """Median (compact) of a summarized {median, ci95} leaf."""
    return f"{node['median']:,.0f}"


def _mci(node: dict, pct: bool = False) -> str:
    med, lo, hi = node["median"], node["ci95"][0], node["ci95"][1]
    if pct:
        return f"{med*100:.2f}% (95% CrI {lo*100:.2f}–{hi*100:.2f}%)"
    return f"{med:,.0f} (95% CrI {lo:,.0f}–{hi:,.0f})"


def _flatten(obj, path, out):
    if isinstance(obj, dict):
        is_leaf = ("value" in obj and not isinstance(obj["value"], (dict, list))) or isinstance(
            obj.get("source"), str)
        if is_leaf:
            out.append((".".join(path), obj))
            return
        for k, v in obj.items():
            _flatten(v, path + [k], out)


def _row(*cells) -> str:
    return "| " + " | ".join(str(c) for c in cells) + " |"


def generate(R: dict[str, Any], constants: dict, conditions: dict) -> None:
    config.ensure_dirs()
    d = R["meta"]["default_assumptions"]
    b = R["burden"]["default"]
    res = R["residual"]
    lib = R["library"]["rollup"]
    mf = R["multifactorial"]
    L: list[str] = []
    A = L.append

    A("# Methods — Global Genetic-Disease Burden × Genetic-Medicine Impact")
    A("")
    A(f"_Auto-generated from the analysis pipeline · Monte-Carlo n={R['meta']['n_draws']:,} · "
      f"pipeline commit `{R['meta']['commit']}` · model version {R['meta']['spec_version']}._")
    A("")
    A("This document describes every input, assumption, formula, and parameter behind the "
      "analysis. All headline figures below are regenerated from the pipeline; the full parameter "
      "provenance and disease catalogue are in the appendices. Contestable judgment calls are "
      "implemented as explicit parameters and reported across their range.")
    A("")
    A("---")

    # 0. Objects
    A("## 1. Overview and objects")
    A("")
    A("The analysis is organized around a **library of serious genetic diseases**, each mapped to "
      "(a) the gene(s)/locus that cause it, (b) inheritance mode, (c) incidence at birth, and "
      "(d) which genetic-medicine interventions can address it. Aggregate burden and "
      "preventability are **derived bottom-up** by summing the library; a parametric "
      "**Monte-Carlo model** provides the calibrated top-down denominator with credible intervals "
      "and the editing-unique residual. Interventions considered:")
    A("")
    A("- **CS** — preconception carrier screening (identifies at-risk couples)")
    A("- **PGT** — IVF + preimplantation genetic testing (embryo selection)")
    A("- **PND** — prenatal diagnosis (+ reproductive decision)")
    A("- **NBS** — newborn screening + early therapy (mitigates disease; does not prevent the birth)")
    A("- **Germline embryo editing**")
    A("")

    # 1. Data sources
    A("## 2. Data sources")
    A("")
    A("Provenance tiers: **A** = open programmatic pull (UN WPP births, WHO GHO, gnomAD v4.1, "
      "World Bank income groups, UNAIDS, Orphanet); **B** = registration/manual query (GBD 2023 "
      "Results Tool, OMIM); **C** = transcribed published tables (Modell & Darlison 2008 "
      "haemoglobinopathies; Bittles/consang.net consanguinity; national screening-program "
      "outcomes; ESHRE PGT; SMA NBS cohorts; cost analyses; PCSK9/CCR5/APOE effect sizes). Every "
      "constant carries `{value, low, high, source, doi, table_or_page, retrieved}`; unknowns are "
      "explicit free parameters, never guesses. The full sourced parameter list is Appendix A.")
    A("")

    # 2. Births
    A("## 3. Denominator: annual births")
    A("")
    A(f"Global annual live births are modelled as **{_mci(R['births_per_year'])}** "
      "(UN WPP 2024; the interval spans the WPP estimate and the ~140M figure used in the draft). "
      "Per-country births distribute to World Bank income groups and GBD super-regions via "
      "population-weighted birth shares.")
    A("")

    # 3. Library
    A("## 4. Disease library")
    A("")
    A(f"The curated catalogue contains **{lib['n_diseases']} serious genetic diseases** across five "
      "categories (autosomal recessive, autosomal dominant, X-linked, chromosomal, multifactorial). "
      "Gene–disease relationships and inheritance modes are established facts (OMIM/Orphanet). "
      "Incidence is expressed per 100,000 live births with a `basis` flag "
      "(`cited` / `textbook_estimate` / `order_of_magnitude`); the Orphanet ingest scales the "
      "catalogue toward full coverage. Bottom-up affected births per disease = "
      "`births × incidence_per_100k / 100000`.")
    A("")
    A(_row("Category", "Affected births/yr (bottom-up)"))
    A(_row("---", "---:"))
    for cat, v in R["library"]["rollup"]["by_category"].items():
        A(_row(cat, f"{v:,.0f}"))
    A(_row("**Catalogue total (lower bound)**", f"**{lib['total_affected_births_per_year']:,.0f}**"))
    A("")
    A(f"The catalogue sum ({lib['total_affected_births_per_year']:,.0f}/yr) is a **lower bound** on "
      "the full denominator — it covers the highest-burden conditions and rises as the library "
      "grows. The calibrated top-down denominator (§5) is the reference total.")
    A("")

    # 4. Burden
    A("## 5. Burden baseline (top-down)")
    A("")
    A("Serious genetic births/year are decomposed into severe **monogenic** disorders and serious "
      "**multifactorial** disorders. Two contestable choices are parameterized and reported across "
      "their range:")
    A("")
    A("- **Severity threshold** — three operationalizations: `def_a` (GBD congenital tree + curated "
      "severe-monogenic list, narrow), `def_b` (\"lethal or lifelong serious disability absent "
      "treatment\", default), `def_c` (DALYs-per-case above threshold, broad).")
    A("- **Attribution stance** for multifactorial disease — `inclusive` (count all cases, g=1), "
      "`heritability_weighted` (g≈0.5), `exclusive` (high-penetrance familial subsets only, g≈0.1). "
      "This choice dominates the denominator and is foregrounded, not buried.")
    A("")
    A(f"Under the default set (severity=`{d['severity']}`, attribution=`{d['attribution']}`):")
    A("")
    A(_row("Quantity", "Median (95% CrI)"))
    A(_row("---", "---:"))
    A(_row("Monogenic serious births/yr", _mci(b["monogenic"])))
    A(_row("Multifactorial serious births/yr", _mci(b["multifactorial"])))
    A(_row("**All serious genetic births/yr**", f"**{_mci(b['total_serious'])}**"))
    A(_row("Share of all births", _mci(b["serious_share_of_births"], pct=True)))
    A("")
    A("The full severity × attribution grid (nine combinations) is emitted to `paper_numbers.json` "
      "and shown in the app's Denominator view.")
    A("")

    # 5. Genetic-medicine status
    st = lib["genetic_medicine_status"]
    A("## 6. Genetic-medicine status")
    A("")
    A("Every disease is placed in one **status** derived directly from its intervention flags — no "
      "weights, no composite score:")
    A("")
    A("- **Preventable & treatable** — an unaffected child is achievable (screening/selection) *and* "
      "effective early therapy exists")
    A("- **Preventable** — an unaffected child is achievable, but no cure")
    A("- **Treatable** — effective early therapy exists, but hard to prevent")
    A("- **Detectable only** — prenatal detection without selection")
    A("- **No current option**")
    A("")
    A("The distribution across statuses — by disease count and by affected births — is the headline "
      "picture of what existing genetic medicine can already do. \"Addressable by existing tools\" is "
      "everything but the empty status.")
    A("")
    A(_row("Status", "Diseases", "Affected births/yr"))
    A(_row("---", "---:", "---:"))
    for s in st["order"]:
        v = st["distribution"][s]
        A(_row(v["label"], v["n_diseases"], f"{v['births']:,.0f}"))
    A(_row("**Addressable by existing tools**", "",
           f"**{st['addressable_by_existing_tools_births']:,.0f} "
           f"({st['addressable_by_existing_tools_share']*100:.0f}%)**"))
    A("")
    A("The editing-unique residual (§8) is deliberately *not* a status here: it is a sliver of "
      "couples *within* diseases (no selectable embryo), not a class of diseases.")
    A("")

    # 6. Preventability engine
    A("## 7. Preventability engine (sequential)")
    A("")
    A("Tools compose in causal order **CS → PGT → PND → NBS**, each acting on the residual of the "
      "last:")
    A("")
    A("```")
    A("remaining_after_t = remaining_before_t × (1 − prevent[c,t] × coverage[t,region,scenario])")
    A("```")
    A("")
    A("Two outcome tracks are carried separately: **averted_birth** (CS, PGT, PND only) and "
      "**averted_burden** (adds NBS, which mitigates the burden of births that still occur, scaled "
      "by the treatable fraction). Full-coverage preventable fractions `prevent[c,t]` are anchored "
      "to national program outcomes (thalassaemia ~90%, Down syndrome ~70%); coverage scenarios are "
      "`current` / `achievable_2035` / `ideal`, refined per income group by an access multiplier "
      "(<1 for LMICs, reflecting that ~94% of birth-defect births occur in LMICs). PND counting is "
      "termination-dependent and reported with the toggle on and off.")
    A("")

    # 7. Residual
    A("## 8. Editing-unique residual (S1 + S2)")
    A("")
    A("**S1 — no selectable unaffected embryo.** The only monogenic configuration where embryo "
      "selection cannot help: recessive affected × affected (aa × aa) couples, or a viable "
      "homozygous-dominant (AA) parent. Per condition, from allele frequency q, penetrance, "
      "survival-to-reproduction s, assortative-mating α, locus-concordance ℓ, and consanguinity F:")
    A("")
    A("```")
    A("P_aa      = q² + F·q·(1−q)")
    A("P_aa_repro = P_aa · s · penetrance")
    A("α_eff     = α · ℓ                          (partner affected AND at the same locus)")
    A("P_couple  = P_aa_repro · (α_eff + (1−α_eff)·P_aa_repro)      # recessive")
    A("births_S1 = births × Σ_conditions P_couple  + structural-variant term")
    A("```")
    A("")
    A(f"Standard both-heterozygous couples (¼ unaffected embryos) are selection-addressable and "
      f"excluded. Result: **S1 ≈ {_mci(res['s1_total'])}** including congenital deafness; "
      f"**{_m(res['s1_total_without_contested'])}** excluding it (deafness is flagged contested — "
      "many in the Deaf community do not regard it as a disease to prevent — and toggled explicitly; "
      "the draft paper's 14,000 sits between the two).")
    A("")
    A("**S2 — editing-superior complex disease.** The multifactorial share for which a single/"
      "oligo-locus edit would uniquely benefit after netting out somatic, pharmacological, and "
      "public-health alternatives, under strict vs permissive criteria: "
      f"strict ≈ {_m(res['s2']['strict'])}/yr, permissive ≈ {_m(res['s2']['permissive'])}/yr.")
    A("")
    A(f"**Uniquely editable total (permissive): {_mci(res['uniquely_editable_total']['permissive'])}"
      f"** — **{_mci(res['uniquely_editable_share_of_serious']['permissive'], pct=True)}** of serious "
      f"genetic disease; the complement, **"
      f"{_mci(res['addressable_share_of_serious']['permissive'], pct=True)}**, is not uniquely "
      "reliant on editing.")
    A("")

    # 8. Multifactorial viability
    A("## 9. Multifactorial intervention viability (liability-threshold)")
    A("")
    A("Multifactorial disease is modelled along a **polygenicity spectrum** (oligogenic → massively "
      "polygenic). On the liability-threshold model, liability ~ N(0,1) and a person is affected "
      "when liability exceeds T = Φ⁻¹(1−K) for lifetime prevalence K. An intervention that lowers "
      "expected liability by δ standard deviations changes risk from K to 1−Φ(T+δ); relative risk "
      "reduction RRR = 1 − (1−Φ(T+δ))/K.")
    A("")
    A("```")
    A("Embryo selection : δ = √(prs_r2 · sib_frac) · E|min of N embryos|      (Blom order statistic)")
    A("Oligo-locus edit : δ = √( oligo_editable_h2 · (1 − e^(−n_edits/τ)) )")
    A("```")
    A("")
    A("Selection power grows with embryo number N; editing power depends on how concentrated risk "
      "is in editable large-effect loci (≈0 for massively polygenic traits). Two technology "
      "scenarios move the frontier: **present** (N≈5 embryos, 1 edit) and **near-future** (N≈200 "
      "via IVM/IVG, ~10 multiplex edits). A `pleiotropy_caution` flag overrides an otherwise-"
      "concentrated editing verdict (e.g. APOE, HLA).")
    A("")
    fr = mf["frontier"]
    A(f"Frontier ({mf['n_diseases']} common complex diseases): **editing viable for "
      f"{fr['present']['editing_viable']} disease(s) today → {fr['near_future']['editing_viable']} "
      f"near-future**; selection viable-or-marginal for "
      f"{fr['present']['selection_viable_or_marginal']} → "
      f"{fr['near_future']['selection_viable_or_marginal']}. Massively polygenic traits "
      "(schizophrenia, major depression) never reach editing-viability regardless of technology.")
    A("")
    A("_Caveats (stated in-app): selection RRR can look large for rare, highly-heritable traits — a "
      "property of the liability threshold, not an achievable program; genetic tractability is "
      "necessary but not sufficient for clinical viability (safety, pleiotropy, effect realism are "
      "separate gates)._")
    A("")

    # 9. Resistance
    hiv = R["resistance"]["hiv"]
    A("## 10. Resistance analysis")
    A("")
    A(f"**HIV:** {_m(hiv['vertical_infections_per_year'])} vertical infections/yr (UNAIDS); "
      f"residual after PMTCT (effectiveness × coverage) ≈ {_m(hiv['residual_after_pmtct'])}/yr — the "
      "only window in which CCR5 germline resistance could uniquely matter. **Cardiovascular:** "
      "statins + somatic PCSK9 inhibition deliver comparable benefit cheaply; unique germline "
      "benefit is small and not reduced to a single count. **Neurodegeneration:** APOE developmental "
      "pleiotropy — no safe, clearly causal embryo-level target; reported as **not computable** "
      "rather than forcing a number.")
    A("")

    # 10. Allocation
    al = R["allocation"]
    A("## 11. Allocation")
    A("")
    A(f"Cost per affected birth prevented: **screening program ${_m(al['cost_per_birth_prevented']['screening_program'])}** "
      f"vs **editing program ${_m(al['cost_per_birth_prevented']['editing_program'])}**. Cost per "
      "DALY averted is derived from DALYs-per-case (pending the GBD pull). Budget scenarios "
      "($1B/$5B/$10B per year) translate these into births prevented under each strategy; screening "
      "dominates editing by ~1–2 orders of magnitude. Cost anchors: Cousens et al. 2010 "
      "(haemoglobinopathy programs), IVF+PGT cycle costs, gene-therapy list prices, PMTCT program "
      "costs; the editing-program overhead is a wide-interval free parameter.")
    A("")

    # 11. Uncertainty
    A("## 12. Uncertainty and sensitivity")
    A("")
    A(f"All quantities are propagated through a Monte-Carlo of **n={R['meta']['n_draws']:,} draws** "
      "(Beta for proportions matched by moments; Lognormal for rates and costs with the stated "
      "value as median and low/high as ~95% bounds). Ratios and shares are computed per draw, so "
      "credible intervals are correct. A deterministic **tornado** swings each judgment call across "
      "its range; the parameters that move the uniquely-editable share most, in order:")
    A("")
    A(_row("Parameter", "Editable share range"))
    A(_row("---", "---:"))
    for r in R["sensitivity"]["tornado"]:
        A(_row(r["parameter"], f"{min(r['low'], r['high'])*100:.2f}% – {max(r['low'], r['high'])*100:.2f}%"))
    A("")

    # 12. Assumptions
    A("## 13. Key assumptions and judgment calls")
    A("")
    A("Each is an explicit parameter with a documented default (see `ANALYSIS_LOG.md` for dated "
      "rationale): severity threshold (§5); attribution stance (§5); penetrance floor for S1; "
      "S2 strict vs permissive criteria; tool ordering and whether PND counts as prevention; "
      "inclusion of congenital deafness in S1; GMI capability weights (§6); multifactorial "
      "technology scenarios and pleiotropy blocks (§9); editing-program cost (§11).")
    A("")

    # 13. Limitations
    A("## 14. Limitations")
    A("")
    A("- The disease library is a curated seed of the highest-burden conditions; bottom-up totals "
      "are a lower bound until the Orphanet/GBD ingest expands it.")
    A("- Several incidence and cost values are `textbook_estimate`/`order_of_magnitude` anchors "
      "pending the GBD 2023 and PGS-Catalog pulls; these are flagged in Appendix A.")
    A("- S1 allele frequencies are global/ancestry-averaged pending the gnomAD ancestry-weighted "
      "pull; regional S1 uses region-specific consanguinity but global allele exposure.")
    A("- Multifactorial architecture parameters (h², PRS R², oligo-editable h²) are literature "
      "anchors; the viability model estimates genetic tractability, not clinical or ethical "
      "permissibility.")
    A("")

    # 14. Reproducibility
    A("## 15. Reproducibility")
    A("")
    A("`make install && make run && make test` regenerates every figure, this document, "
      "`results/paper_numbers.json`, and `results/tables.md` from the raw constants and library. "
      "`make ingest` pulls the Tier-A sources (see `DATA_NEEDED.md`). The webapp "
      "(`make app-build`) is a static, URL-shareable view of the same emitted data.")
    A("")

    # Appendix A: parameters
    A("## Appendix A — Full parameter provenance")
    A("")
    A(_row("Parameter", "Value", "Low", "High", "Source", "DOI / page"))
    A(_row("---", "---:", "---:", "---:", "---", "---"))
    flat: list = []
    _flatten(constants, [], flat)
    for path, leaf in flat:
        val = leaf.get("value", "")
        src = leaf.get("source", "") or ""
        doi = leaf.get("doi", "") or ""
        page = leaf.get("table_or_page", "") or ""
        ref = doi if doi and doi != "n/a" else page
        A(_row(f"`{path}`", val, leaf.get("low", ""), leaf.get("high", ""),
               str(src)[:70], str(ref)[:40]))
    A("")

    # Appendix B: catalogue
    A("## Appendix B — Disease catalogue")
    A("")
    A(_row("Disease", "Gene(s)", "Inheritance", "Severity", "Births/yr", "Status", "Incidence basis"))
    A(_row("---", "---", "---", "---", "---:", "---", "---"))
    for x in R["library"]["diseases"]:
        A(_row(x["name"], ", ".join(x["genes"]) or "—", x["inheritance"], x["severity"],
               f"{x['affected_births_per_year']:,.0f}", x["status"]["label"], x["incidence_basis"]))
    A("")

    with open(config.RESULTS_DIR / "methods.md", "w", encoding="utf-8") as fh:
        fh.write("\n".join(L))
